# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\2020_12_code_project\Q4\Q4.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Q4(object):
    def setupUi(self, Q4):
        Q4.setObjectName("Q4")
        Q4.resize(320, 240)
        self.centralwidget = QtWidgets.QWidget(Q4)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(10, 10, 301, 221))
        self.pushButton.setObjectName("pushButton")
        Q4.setCentralWidget(self.centralwidget)

        self.retranslateUi(Q4)
        QtCore.QMetaObject.connectSlotsByName(Q4)

    def retranslateUi(self, Q4):
        _translate = QtCore.QCoreApplication.translate
        Q4.setWindowTitle(_translate("Q4", "Q4"))
        self.pushButton.setText(_translate("Q4", "4.1 Stereo Disparity Map"))
