# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\2020_12_code_project\Q3\Q3.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Q3(object):
    def setupUi(self, Q3):
        Q3.setObjectName("Q3")
        Q3.resize(400, 400)
        self.centralwidget = QtWidgets.QWidget(Q3)
        self.centralwidget.setObjectName("centralwidget")
        self.Button = QtWidgets.QPushButton(self.centralwidget)
        self.Button.setGeometry(QtCore.QRect(40, 100, 321, 171))
        self.Button.setObjectName("Button")
        Q3.setCentralWidget(self.centralwidget)

        self.retranslateUi(Q3)
        QtCore.QMetaObject.connectSlotsByName(Q3)

    def retranslateUi(self, Q3):
        _translate = QtCore.QCoreApplication.translate
        Q3.setWindowTitle(_translate("Q3", "Q3"))
        self.Button.setText(_translate("Q3", "3. Augmented Reality"))
