# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\2020_12_code_project\Q1\Q1.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Q1(object):
    def setupUi(self, Q1):
        Q1.setObjectName("Q1")
        Q1.resize(260, 230)
        self.centralwidget = QtWidgets.QWidget(Q1)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 241, 171))
        self.groupBox.setObjectName("groupBox")
        self.Button_1_1 = QtWidgets.QPushButton(self.groupBox)
        self.Button_1_1.setGeometry(QtCore.QRect(10, 20, 221, 23))
        self.Button_1_1.setObjectName("Button_1_1")
        self.Button_1_2 = QtWidgets.QPushButton(self.groupBox)
        self.Button_1_2.setGeometry(QtCore.QRect(10, 50, 221, 23))
        self.Button_1_2.setObjectName("Button_1_2")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 100, 221, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 120, 221, 16))
        self.label_2.setObjectName("label_2")
        self.CloseButton = QtWidgets.QPushButton(self.centralwidget)
        self.CloseButton.setGeometry(QtCore.QRect(170, 190, 75, 23))
        self.CloseButton.setObjectName("CloseButton")
        Q1.setCentralWidget(self.centralwidget)

        self.retranslateUi(Q1)
        self.CloseButton.clicked.connect(Q1.close)
        QtCore.QMetaObject.connectSlotsByName(Q1)

    def retranslateUi(self, Q1):
        _translate = QtCore.QCoreApplication.translate
        Q1.setWindowTitle(_translate("Q1", "Q1"))
        self.groupBox.setTitle(_translate("Q1", "1. Find Contour"))
        self.Button_1_1.setText(_translate("Q1", "1.1 Draw contour"))
        self.Button_1_2.setText(_translate("Q1", "1.2 Count coins"))
        self.label.setText(_translate("Q1", "There are __ coins in coin01.jpg"))
        self.label_2.setText(_translate("Q1", "There are __ coins in coin02.jpg"))
        self.CloseButton.setText(_translate("Q1", "Close"))
