# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\2020_12_code_project\Q2\Q2.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Q2(object):
    def setupUi(self, Q2):
        Q2.setObjectName("Q2")
        Q2.resize(370, 172)
        self.centralwidget = QtWidgets.QWidget(Q2)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 351, 151))
        self.groupBox.setObjectName("groupBox")
        self.Button_2_1 = QtWidgets.QPushButton(self.groupBox)
        self.Button_2_1.setGeometry(QtCore.QRect(20, 20, 131, 31))
        self.Button_2_1.setObjectName("Button_2_1")
        self.Button_2_2 = QtWidgets.QPushButton(self.groupBox)
        self.Button_2_2.setGeometry(QtCore.QRect(20, 60, 131, 31))
        self.Button_2_2.setObjectName("Button_2_2")
        self.Button_2_4 = QtWidgets.QPushButton(self.groupBox)
        self.Button_2_4.setGeometry(QtCore.QRect(20, 100, 131, 31))
        self.Button_2_4.setObjectName("Button_2_4")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setGeometry(QtCore.QRect(170, 19, 171, 121))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setGeometry(QtCore.QRect(20, 20, 61, 16))
        self.label.setObjectName("label")
        self.Button_2_3 = QtWidgets.QPushButton(self.groupBox_2)
        self.Button_2_3.setGeometry(QtCore.QRect(20, 80, 131, 31))
        self.Button_2_3.setObjectName("Button_2_3")
        self.comboBox = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox.setGeometry(QtCore.QRect(20, 40, 67, 22))
        self.comboBox.setModelColumn(0)
        self.comboBox.setObjectName("comboBox")
        Q2.setCentralWidget(self.centralwidget)

        self.retranslateUi(Q2)
        QtCore.QMetaObject.connectSlotsByName(Q2)

    def retranslateUi(self, Q2):
        _translate = QtCore.QCoreApplication.translate
        Q2.setWindowTitle(_translate("Q2", "Q2"))
        self.groupBox.setTitle(_translate("Q2", "2. Calibration"))
        self.Button_2_1.setText(_translate("Q2", "2.1 Find Corners"))
        self.Button_2_2.setText(_translate("Q2", "2.2 Find Intrinsic"))
        self.Button_2_4.setText(_translate("Q2", "2.4 Find Distortion"))
        self.groupBox_2.setTitle(_translate("Q2", "2.3 Find Extrinsic"))
        self.label.setText(_translate("Q2", "Select Image"))
        self.Button_2_3.setText(_translate("Q2", "2.3 Find Extrinsic"))
